#!/bin/bash

echo "=========================================="
echo "🔐 Setup GitHub Secrets for Firebase"
echo "=========================================="
echo ""
echo "Open this URL in your browser:"
echo "https://github.com/Arnonfr/cook-it/settings/secrets/actions"
echo ""
echo "Add these 2 secrets:"
echo ""
echo "1. Secret name: FIREBASE_SERVICE_ACCOUNT"
echo "   Value: (copy from below)"
echo ""
echo "--- COPY START ---"
cat /Users/hyh/Documents/cookit/scripts/firebase-service-account.json
echo ""
echo "--- COPY END ---"
echo ""
echo "2. Secret name: FIREBASE_APP_ID_ANDROID"  
echo "   Value: 1:629153402724:android:fb933cd078c975a42c3471"
echo ""
echo "=========================================="
echo "After adding both secrets, push to trigger build:"
echo "  git add .github/workflows/android-distribution.yml"
echo "  git commit -m 'Setup Firebase App Distribution'"
echo "  git push"
echo "=========================================="
